# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 130)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icono/icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(40, 45, 190, 20))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.label_url = QtWidgets.QLabel(self.centralwidget)
        self.label_url.setGeometry(QtCore.QRect(10, 50, 30, 13))
        self.label_url.setObjectName("label_url")
        self.pushButton_descargar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_descargar.setGeometry(QtCore.QRect(235, 44, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/descargar/descargar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_descargar.setIcon(icon1)
        self.pushButton_descargar.setObjectName("pushButton_descargar")
        self.labelstatusbar = QtWidgets.QLabel(self.centralwidget)
        self.labelstatusbar.setGeometry(QtCore.QRect(110, 70, 47, 13))
        self.labelstatusbar.setText("")
        self.labelstatusbar.setObjectName("labelstatusbar")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(10, 10, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebDownloader"))
        self.lineEdit_url.setPlaceholderText(_translate("MainWindow", "https://www.google.com/"))
        self.label_url.setText(_translate("MainWindow", "URL:"))
        self.pushButton_descargar.setText(_translate("MainWindow", "Descargar"))
        self.label_titulo.setText(_translate("MainWindow", "Web Downloader"))
import descargar_rc
import icono_rc
